### ISSUE TITLE
Supporting construction of web site

### ISSUE THREAD

**Issue by qcjxberin** [chkr1011/MQTTnet#1]
Supporting construction of web site

**Comment by chkr1011** [comment]
Hi, 
sorry but I don't know what you mean with this.

Best regards
Christian Kratky

**Comment by chkr1011** [comment]
Hi,
can you please give me some hints about this issue?

Best regards,
Christian

**Comment by qcjxberin** [comment]
Sorry, what i mean when it can support websocket

**Comment by chkr1011** [comment]
Hi, 
this is not planned yet. In general this is supported because the transport layer can be injected. 
But there are several HTTP libraries which are already  supporting WebSockets. So it can be a wrapper for such libraries or a full implementation of the websocket protocol. But this also requires HTTP etc. which is a big change then.

For which platform do you need it? 

Best regards
Christian

**Comment by qcjxberin** [comment]
maybe .net framework or .net core

**Comment by qcjxberin** [comment]
Do i need this function more urgent, can I increase the priority?

**Comment by chkr1011** [comment]
Sorry no. But I will try it in the next few weeks. At least for client-side support.
But you can also create a pull request if you wan't to implement it.

Best regards
Christian
