### ISSUE TITLE
 Did not receive any packet or keep alive signal.

### ISSUE THREAD

**Issue by maikebing** [chkr1011/MQTTnet#1016]
ID:,ThreadId:55,Source:MqttClientKeepAliveMonitor,Timestamp:10/29/2020 05:15:37,Message:Client '4051lbJWH1Q71o7sMOCz10324xAia97O': Did not receive any packet or keep alive signal

Why is this error occurring? How to avoid it?

**Comment by chkr1011** [comment]
This happens when the server did not receive a PING or any other message from the client. The duration is specified in the KeepAlive value when connecting. I assume your device is not sending any data anymore.

Please try with the latest version. If the problem still exists please reopen this ticket.
