### ISSUE TITLE
Publish status

### ISSUE THREAD

**Issue by pehachem** [chkr1011/MQTTnet#173]
Hi Christian,
Since, as far I can see, there is no TResult on PublishAsync(), nor "Published event" fired, how do you recommend to check if a given message has been succesfully published?
This question rises in case where Deconnected() is fired quite simultaneusly: had the given message been published or not? My opinion is that at least QoS 1 and 2 should allow for this kind of flow control... and QoS 0 may take profit of it to manage resources.
Thanks in advance,
Philippe.

**Comment by chkr1011** [comment]
Hi Philippe,
if you call _PublishAsync_ you will get an Exception when sending fails. 
The _ManagedClient_ has no indicator (yet) if a message was sent or not (but they can be persisted).

Best regards
Christian

**Comment by pehachem** [comment]
Hello Christian, and thanks for your answer.
In fact, I am using your MQTT client for messaging between [software agents](https://en.wikipedia.org/wiki/Software_agent) through a shared MQTT broker.
I am using the _regular_ MqttNet client because I need both to keep mastership of resources consumption - whatever be the state of the connection - as well as to control retry strategy directly from the application level. For these reasons, I will probably not use the _managed_ MqttNet client.
I am really interested in getting a publication status for each message - succeeded or failled - so that the application is able to take the appropriate decision, which may depend on the message content itself (and may or may not imply retrying). A publishing event, carrying the sending status associated with each submitted payload, would be great...

By the way, many thanks for your usefull job :-)
Best regards,
Philippe.

**Comment by chkr1011** [comment]
Hi @pehachem,
I will add an event which is fired if a message was processed and transmitted. From the topic and payload you must get the information you need. I hope this helps. I will also add another event which is called if the transmit has failed (including an exception). 

Best regards
Christian

**Comment by pehachem** [comment]
Hi Christian, and thanks for your answer.
Sure, it will help! These are very good news for me, and I am eager to test this release ;-)
Many thanks in advance,
Philippe.

**Comment by duncanellison** [comment]
Hi Christian,

What's the status on this as I am keen to test?  I'm using 2.7.1-rc1 from NuGet, but I'm not seeing any new events, are they in there yet ?

Duncan

**Comment by chkr1011** [comment]
Hi @duncanellison,
I added this event for the _ManagedClient_. For the regular client you just need to catch every exception when using the _PublishAsync_ method. If there is no exception the message was delivered successfully. Otherwise you will get an exception and you can do whatever you want to. You can build your own event for this for example.

Best regards
Christian

**Comment by duncanellison** [comment]
I'm struggling to find the event, is it  'ApplicationMessageProcessed' ?

**Comment by chkr1011** [comment]
Yes this is the new event.

**Comment by hasleyfang** [comment]
Hi @chkr1011,

I'm using ManagedClient 2.8.5 and I found something weird. FYI, I need to monitor every PublishAsync call to make sure messages are delivered to the server. So I use the HasSucceeded or HasFailed property of ApplicationMessageProcessedEventArgs in the ApplicationMessageProcessed event to determine the status.

However, I found the total number of respond received (HasSuceeded and HasFailed) from ApplicationMessagedProcessed event will always more than the total number of PublishAsync call. Is it due to the logic behind of PublishAsync call will auto publich again when connection is disconnected or publish is failed? If the answer is yes, then I should able to get the total of HasSuceeded count same with the total of PublishAsync count. But when I  monitor the HasSuceeded flag only, my system could not proceed due to web socket or client is disconnected while waiting for the HasSuceeded respond. May I know how do i ensure the connection can persist until last HasSuceeded respond return?

**Comment by liaoliaoda** [comment]
Hi @hs84 ,

have you solve that problem, I have the same problem too.

Many thanks for any response.

**Comment by liaoliaoda** [comment]
Hi @chkr1011,

the HasSucceeded's value is always true in ApplicationMessageProcessedHandler when msg is published include success or fail. 

Thanks.

**Comment by chkr1011** [comment]
First of all the flag indicates that there was simply no exception. So no exception leads to a "success". 

@liaoliaoda How do you identify the failure in your case? This lib only tells you that the message was sent to the broker successfully (no exception). So do you get an exception? If yes, which?

**Comment by liaoliaoda** [comment]
Hi @chkr1011 ,

Here is no exception. I have solved that problem. Thanks for your repply.
