### ISSUE TITLE
MQTTnet vs RabbitMQ

### ISSUE THREAD

**Issue by biapar** [chkr1011/MQTTnet#193]
Hi,
I'm in a evaluation phase between the good MQTTnet c# lib to build a simple and growing MQTTnet service with some policies and the big RabbitMQ. 
Which is your opinion?
Thanks.

**Comment by chkr1011** [comment]
Hi,
in my opinion your question is not easy to answer because RabbitMQ is AMQP and MQTTnet is MQTT. So the protocols are different (I don't know if RabbitMQ also implements MQTT but I guess not). 

The big advantage of MQTTnet is that you can host a server in your own software and implement lots of extensions around it. RabbitMQ and other MQTT brokers are closed services which implement all the official MQTT features but you cannot host it on your own application and you have to use loopback connections from the same machine etc.

Best regards
Christian

**Comment by biapar** [comment]
Thank you for your reply. RabbitMQ has a MQTT plugin, but I think is a lot fat and our platform will be on c# stack.

**Comment by JTrotta** [comment]
Try ActiveMQ. With  an esb linked.
