### ISSUE TITLE
Broker Server: How to use into a web .NET Core 2 / Standard proejct?

### ISSUE THREAD

**Issue by biapar** [chkr1011/MQTTnet#206]
How to use Broker Server into a web .NET Core 2 / Standard proejct?
Or better to build a "standard" or "console" application for only broker?  If yes, I think that I've to use MQTTClient into web project to connect to MQTT Broker. Is right?

**Comment by rshillington** [comment]
I think what you're looking for are two projects, one to be the server, and one to be the client.

If you're wanting to use WebSockets then you'll need the server project to be an ASP.NET Core and you'll need to reference the mqttnet.aspnetcore package as well as mqttnet

**Comment by biapar** [comment]
My idea is to build and have a .net standard broker server and the client is web/rest to present data or send command. Or Do you suggest to have a web broker server with a lots iot clients connected?

**Comment by biapar** [comment]
Is there an example of a MQTTnet asp.net core web client?

**Comment by JanEggers** [comment]
I would use mqtt like in the sample project with mqttjs in the browser, why would you want to wrap that in webapi? 

if you have many clients i would use hivemq, azure iot hub or similar. this package does not have a skaleout mechanic so if a single server cant handle the load you are screwed. (Sidenote: I switched to UTF8.Json for payload serialization because for my messages that was 10 times faster than Json.Net) 

im currently playing around with signalr / creating a mqtt transport for signalr but that is just prototyping stage.

**Comment by biapar** [comment]
Hi, thanks.
Azure iot is planned in the future, but I need something that we can “control”.
Do you suggest that client talk direct to mqqt server without passing trough web api core?
At this stage I integrated signalR into web api core 2 and send info to Angular 5 client.

**Comment by biapar** [comment]
Ok. I’ll try your suggestion and use web api for the other bussines api need by client.
You can made a push/ pull with SignalR Hub or Socket.io.

**Comment by JanEggers** [comment]
you dont need signalr there is a websocket mqtt js library to publish messages or subscribe to updates.

https://github.com/chkr1011/MQTTnet/blob/54a0265ef9ca6ce82efdb4d6d3d061d3fad70b5f/Tests/MQTTnet.TestApp.AspNetCore2/package.json#L9 

https://github.com/chkr1011/MQTTnet/blob/54a0265ef9ca6ce82efdb4d6d3d061d3fad70b5f/Tests/MQTTnet.TestApp.AspNetCore2/wwwroot/app/app.ts#L3-L56

**Comment by biapar** [comment]
Yes, if you don’pass trough web api.
