### ISSUE TITLE
Code Review: Shouldn't async be used in Task.Run when action inside is awaitable?

### ISSUE THREAD

**Issue by ahmadalli** [chkr1011/MQTTnet#238]
take a look at this line:

https://github.com/chkr1011/MQTTnet/blob/ffb1645f149f3afd69765e1e5c2e59a5afa389a6/Frameworks/MQTTnet.NetStandard/Client/MqttClient.cs#L491

shouldn't it be this?
```c#
Task.Run(async () => await ProcessReceivedPacketAsync(packet), _cancellationTokenSource.Token);
```

**Comment by chkr1011** [comment]
Hi,
thanks for reporting but I assume it is not required. The _Task.Run_ method has a overload which receives the returning Task (Func<Task>) so that internally the Task is properly executed. Adding a _async/await_ here will only perform a context switch (including serialization etc.) ending up with doing nothing because after the _await_ there is no more code.
Best regards
Christian

**Comment by ahmadalli** [comment]
Hi :)
That's right. Sorry to bother you :)
