### ISSUE TITLE
Message dispatch on server

### ISSUE THREAD

**Issue by israellot** [chkr1011/MQTTnet#239]
I want to improve message dispatching on server, but I would like to discuss it a bit. 
Currently ( and correct me if I got it wrong ) a message will be sent to all client sessions and those will iterate all subscriptions to decide whether to forward or discard a message. This approach seems reasonable for a small number of clients and a small number of subscriptions. My concern is that if clients have many subscription and client count is also high, this can start to be a bottleneck. 
I would be looking at some strategies, from the top of my head:

1) A global hash dictionary for exact subscriptions. Sessions would register themselves on the directory. This would improve the use case of exact topic subscriptions. 

2) A tree directory for wildcard subscriptions, decomposing the arriving topic by levels, we can subset the sessions to test it against 

3) Caching hits and misses ( need better thinking )

I believe we could also setup some scenarios tests to give us perspective on the impact of those changes, or even if they are needed at all. Mostly to test when there are many subscriptions and messages hit many vs few of them. 
 
What do you think?

**Comment by chkr1011** [comment]
I agree to @JanEggers suggestion. I already created a project with BenchmarkDotNet. It looks good to me. Very cool library. With this library we have a tool to _validate_ code changes if they are worth it. 

@israellot I also reviewed the changed topic comparer. I agree your suggestion but I have doubts if this is a good idea because the code is, compared to the old one, very very long and difficult to maintain. If you can measure the difference with BenchmarkNotNet we can make a decision and compare performance vs. code maintenance.

**Comment by israellot** [comment]
I understand your concern about maintainability. Hopefully this is one of those specialized sections that are very settled. Once enough unit tests are written, it will be sitting there for ages before the need to touch it arrives. In general, I am concerned about the amount of allocations we do for each message to be processed, and I will try to reduce that starting from those low side effect sections. 
I also have some ideas on reusing buffers that I'll try to implement once I get the time.
