### ISSUE TITLE
How to pass a token as authentication? No into a password field.

### ISSUE THREAD

**Issue by biapar** [chkr1011/MQTTnet#255]
I need a suggestion.
How to pass a token as authentication? No into a password field or payload, because into a payload mean that the device is already connected.

**Comment by rshillington** [comment]
Why not pass the token as the Username, and then in the ServerOptions provide a ConnectionValidator 
```
var mqttServerOptions = new MqttServerOptionsBuilder()
            .WithConnectionValidator(context => ValidateConnection(context))
            .WithSubscriptionInterceptor(context => SubscriptionInspector(context))
            .Build();
```
where `ValidateConnection` and `SubscriptionInspector` are routines that you would write to make validate the token found in context.Username

**Comment by biapar** [comment]
Ok. And If I want a second layer of authentication I can pass:

`username = <login>||<token>;
 password = <password>`

Maybe?

**Comment by rshillington** [comment]
What you do in the ValidateConnection function can be as simple or as complex as needed.  The second layer, as you call it could come in the SubscriptionInterceptor.  The idea being that just because the user is valid, doesn't mean said user is able to subscribe to that specific topic.

The problem you may find in validating the Subscriber is that all you have to go on is the ClientId -- so I think you have to cache some sort of mapping of ClientId to User so that you can then determine by user if the subscription request should be accepted.

**Comment by biapar** [comment]
Thanks. I understand. @rshillington thanks for you fast response.

**Comment by JTrotta** [comment]
Why don't use ManagedClient? It has been projected for this purpose.

**Comment by biapar** [comment]
So the clients will be hardware clients and I'm not develop their firmware and the firmware must be in c#.
