### ISSUE TITLE
Could not build the project!

### ISSUE THREAD

**Issue by genckenan** [chkr1011/MQTTnet#306]
I don't know why, but I can not build the project. I am using Visual Studio's last version. It always says "can not find project info for C:\\....\filename.csproj " but project is there. How can I solve the problem?

**Comment by smuellener** [comment]
I too have some issues loading the csprojs into recent version of VisualStudio. @chkr1011 Would you be open for a suggestion of new solution structure? Maybe with file paths that that correspond to the namespaces?

**Comment by chkr1011** [comment]
@genckenan Do you have some more details like screenshots or logs? Also please let me know which system you use (Windows or Linux).
Please test with the _develop_ branch because there are some duplicate file issues solved.

@smuellener I will rename some folders and projects according to the new structure. These names historical and do not reflect the architecture. But this should not affect your problems. Also please provide some more details.

Best regards
Christian

**Comment by genckenan** [comment]
@chkr1011 Thanks for quick response. I have just tested the issue with develop branch and I could built it just fine. By the way I am using Windows 10 Home edition. 

Best Regards,
Kenan

**Comment by smuellener** [comment]
@chkr1011 Excellent thank you. This should be fine then.
