### ISSUE TITLE
Integration into Orleans

### ISSUE THREAD

**Issue by dealproc** [chkr1011/MQTTnet#392]
For Backplane usage, I am considering learning both this library (simple spike worked, thanks) and using Orleans as a way to broker messages, etc. between a front-end and a cluster of MQTTnet servers.

If I go this route, would someone be willing to discuss connection lifetimes or similar?  I believe we would be able to implement this similar to how the SignalR Orleans library is implemented.

My difficulty is that without inline or other docs, I'm not sure where/how to draw parallels between SignalR and MQTTnet.  I do realize that the concept of "users"; "groups"; and "clients" is not available with MQTTnet, but I believe that outside of that restriction, there is enough similarity where this would indeed be possible.

I would suspect then that you would use sticky sessions within your nginx configuration, and subsequently have what you need end-to-end.

Feedback is welcome/encouraged on this hair-brained idea.

Thanks.

**Comment by dealproc** [comment]
Can you discuss a little more in-depth, @JTrotta on how you've implemented?  Trying to determine if Orleans is going to be overkill for my needs or not, which is why I'm inquiring.

**Comment by JTrotta** [comment]
@dealproc, well yes of course, but I do not think this is the best place. I will try to give you some hints now, then we can discuss on the complete project I'm using.
First of all this library is a very good client, but as server side there are already many others, older, proved in production and stable app. As far as the server side of this library will not become stable and 'old', I do not suggest you to use it in a production environment (even if I did sometimes, because I like it). ActiveMQ is the best and complete AMQP server on the market, and can be used with no pain on Linux servers. 
I realized a mixed architecture called ENNIO. Basically it's a cluster of CentOS servers. All servers are perfectly equals, they have the same cpu/ram/disk and the same applications, they are omomorphic  and, more over, we say that they live in a 'democratic' cluster: there is no server with more rights than others. 
Each server has some (five/six) services: **ActiveMQ** as AMQP front-end, **AKKA**.net based application working as microservices ESB, **NGinx** and **ASP**.net as web server and application, **Postgres** sql as relational DB, and **ElasticSearch** as NON-Relational DB.
Each service has its own cluster architecture, and the whole cluster is arbitrated by the ESB I wrote in AKKA.net. The idea is that in a modern enviroment you need: a AMQP server (a broker) to manage the mass clients connections and messages, than those messages must be managed by an ESB (correctness, ACL, routing, etc), then you need to persist them somewhere on (today) a non relational DB. Finally you would need a CMS to manage the cluster or the application you want realiaze over the cluster.
In this way your architecture has got High Availability (HA) and is Fault Tolerant (FT). HA and FT today are a MUST. ENNIO  (the architecture I realized and exposed) is HA because you can distribute the load over the cluster servers at EACH level (broker, web application, DB ), it's FT because if a server goes down the others can manage the load, and no data is lost (DB are syncronized inside the cluster).
The best is that you can add/remove a cluster server during the production without problems (hot switching server). I have now a production system with 5 servers in cluster, managing million of messages coming from MQTTNet clients. When the clients grow up (as everyone expects) you can add a server switching it on, it will found the cluster by it's own and will enter the cluster receiving data from DBs. When the clients decrease you can switch off a server to save energy. 
That's all.
JJ

**Comment by dealproc** [comment]
@chkr1011 Not sure how to get a dialog with you, but if you would happen to have some time, I'd like to discuss this with you and see if we can't get something going.  I believe that this would be a rather simplistic implementation once I understand the server library and where all the hook points are at.  I think, at the end, it's going to be using one of the `OnClientConnected` calls and capturing the connection, "subscribing to it", and letting the silo know about it.... but am unsure.

**Comment by dealproc** [comment]
If anyone is interested... this is what I came up with... I still need to test it, etc., but it seems to work as you would expect so-far. https://github.com/dealproc/MQTTnet.Orleans

**Comment by JanEggers** [comment]
looks interesting was thinking to use orleans too but didnt have the time yet to investigate

**Comment by dealproc** [comment]
Yea... I took inspiration from the signalr orleans backplane to bring this online.  so far, it seems to be working... need to get the docker nodes into a 'production' environment and load-test it.  what's nice with the Orleans implementation is that you don't seem to need as much plumbing as you would with other ways for things like the Online status of the device, etc.

**Comment by dealproc** [comment]
I'm going to close this... @chkr1011 If you want to add this to a "group" where we can move the MQTTnet project into as well... let me know, as i would be willing to provide MQTTnet.Orleans into that group as well.  If others have extension/helper projects for MQTTnet, it may indeed make sense to push it all into a group/org to make it easier to discover long-term.
