### ISSUE TITLE
Encryption protocol support?

### ISSUE THREAD

**Issue by PaulFake** [chkr1011/MQTTnet#415]
Hello,

It looks like the encryption protocol is hard-coded to TLS 1.2 in MqttTcpChannel.cs.  I'm curious why 1.0 and 1.1 aren't supported.  Also, when more protocols become available in the future, will it be possible to OR the enums and allow support for multiple?

**Comment by GieltjE** [comment]
I agree that this setting should be exposed to allow future upgrades without recompilation.

But why would you still use anything below 1.2?

**Comment by PaulFake** [comment]
I wouldn't do that personally, but we don't know what our clients are expecting us to support.

**Comment by chkr1011** [comment]
I am not sure if this is a good idea because TLS 1.0 and 1.1 are no longer secure. There is already a change in .NET disabling these versions (https://medium.com/@kyle.gagnet/your-net-code-could-stop-working-in-june-afb35fbf29ca) in the future. 

But I get the point that devices my only support 1.0 and they will not be updated.

**Comment by PaulFake** [comment]
Ok, I see Jan added support for this.  Thanks!
