### ISSUE TITLE
Can I put on azure my own MQQT service?

### ISSUE THREAD

**Issue by BartlomiejLeja** [chkr1011/MQTTnet#453]
Hey, guys first of all great job with this MQTT  lib it's awsome, but
I have question can I publish asp .net core app that have MqttServer on azure and it will work?
Ofc I tried locally and it works but on azure I cannot connect with my service. I am not even sure whats the  correct  name of tcp server on azure, on local env it was ip of local machine that runs the MQTT server but on azure I thought that it is adres of my web app.

**Comment by chkr1011** [comment]
Hi yes you can run it as a App Service. The default port should be reachable then. But you need the address of the app service.

Best regards
Christian

**Comment by BartlomiejLeja** [comment]
Thanks for quick response :) Ok, so now I know for sure that my MQTT broker is working on azure because  I' am sending in while loop message and thanks to server.ApplicationMessageReceived I can see it in my logs.  I' am using this set up

var mqttServerOptions = new MqttServerOptionsBuilder()
                .WithoutDefaultEndpoint()
                .Build();
            services
                .AddHostedMqttServer(mqttServerOptions)
                .AddMqttConnectionHandler();

But still I don't know how to configure client. This is the service dashboard. 
![image](https://user-images.githubusercontent.com/25252203/47258317-e01ecd80-d499-11e8-87b4-2b8d75d1db0a.png)

I tried to use  url as name of the service
 var options = new MqttClientOptionsBuilder()
                .WithTcpServer("nameFromPhoto.scm.azurewebsites.net")
                .Build();
but it dosent work. Have you ever published that kind of MQTT broker on azure ? Can you give me some more tips?
Best regards
Bartlomiej

**Comment by dealproc** [comment]
You don't have much information here.  Have you looked at the samples for the dotnet core configuration where you have to do the configs, set ports, etc.?

If you are configuring to use an app service in Azure, unless something has changed, you typically get only ports 80/443 to host applications on.  If you need a custom port number for your application, you may need to host the project in a dedicated VM or something similar where you can adjust the firewall ports more granularity.  Now, I say this and I advise that you should take this with a grain of salt, as I am not an expert in Azure, so you may find a way to do what I have not (adjust the firewall rules on an app service).  I'm personally rolling over to using web sockets instead of tcp sockets as it should allow me to connect using :443 at the end instead of needing to maintain a custom port.

Curious to hear back to see what else you have discovered.

**Comment by BartlomiejLeja** [comment]
Hi, dealproc thx for advices. And yes you have right only 80 and 443 ports are open and maybe some others but only for debug purpose. After intensive  research I'am almost sure that opening other ports on web sevice isn't possible ;(. VM is good idea, but not if you have only university account on azure ;p. I have implemented on this server signalR core that use web sockets  but I a want to have publish subscribe pattern from esp 8266 that have  PubSubClient lib directly to cloude but for know I think it's not possible for me and I will have local MQTT broker on raspberry pi 3 (on windows 10 iot)

**Comment by chkr1011** [comment]
We also use App Services with different ports. They are not limited to 80 and 443. Maybe you need a higher tier?

**Comment by chkr1011** [comment]
Sorry but I was wrong. It is limited to 80 and 443.
