### ISSUE TITLE
Wrong or missing Sender ClientId

### ISSUE THREAD

**Issue by janmegert** [chkr1011/MQTTnet#459]
```cs
//...
var factory = new MqttFactory();
_mqttClient = factory.CreateMqttClient();
//...
_mqttClient.ApplicationMessageReceived += MessageReceived;
//...
private static void MessageReceived(object sender, MqttApplicationMessageReceivedEventArgs e)
{
    var client = e.ClientId; // <<---- this is my ClientId, not the Sender-ClientId
}
```

Or how would I be able to identify the sender here?

Thx
Jan

**Comment by chkr1011** [comment]
Hi,
the ClientId is not available in your scope. It is:
1. Your client ID when using the Client.
2. The sender when the server receives a messages.
3. Null when the server published the message.

It is not possible to receive the ClientId because it is not transmitted to the clients (but you can add it to your payload instead).

Best regards
Christian
