### ISSUE TITLE
Feature Request: Transport Fallback for the client

### ISSUE THREAD

**Issue by dealproc** [chkr1011/MQTTnet#462]
It seems that given the library can support both WebSockets as well as TCP based connections, it would be highly beneficial if the library could, by default, choose a pecking order (with TCP most likely being the preferred, and WebSockets being the fallback) for using various transports.  The benefit of this is that it abstracts the integrator the need to determine if one works over the other, etc.

WebSockets will probably be favorable in scenarios where most ports are, by default, blocked by a firewall (think corporate setups in this case) whereas 443 is typically still allowable to be used.

**Comment by chkr1011** [comment]
Hi,
do you mean in the Client or Server?
Best regards
Christian

**Comment by dealproc** [comment]
For the client.  The server, we would just host MQTT on TCP 1883; and WebSockets on 443, as one would.  Right now, we are 100% WebSockets only because it is the more compatible when dealing with weird scenarios.

**Comment by SeppPenner** [comment]
What's the status of this?

**Comment by chkr1011** [comment]
In my opinion this should not be added to the library because in my opinion it is hard to define a globally accepted approach. Choosing a fallback might be different for all users. But you can wrap the MQTTClient and when an exception is fired on connect you can try to connect using your fallback server. This can be easily "added" on top of the MQTTClient by encapsulating.
