### ISSUE TITLE
Refactor for full async pipeline

### ISSUE THREAD

**Issue by dealproc** [chkr1011/MQTTnet#506]
I'm reviewing the code base, and i'm noticing calls that are Task-based, but the code is calling `GetAwaiter().GetResult()`.  This creates a sync context, in essence, and can potentially cause hang-ups both server and client side.

Would there be interest in having the entire system walked through and refactored to be asynchronous in nature?  I am presuming that this would create many breaking changes, and would create a full version bump, The benefit would be [potentially] better usage of threads and resources on both the server and client.

**Comment by dealproc** [comment]
To keep the system backward-compatible, we can look into using a utility function to keep the sync calls (e.g. Stop() on MqttClientSession, mark it as [Obsolete], and factor-in a StopAsync() pipeline that will do the work).  I've seen this in a few projects, including IdenttiyServer.

**Comment by dealproc** [comment]
Idle hands being the devil's playground and all... Starting to experiment on the refactor.. here's where I'm at. https://github.com/dealproc/MQTTnet/commits/async

Adding it as a submodule to my main project and will do a full integration and subsequent testing to see if this makes any good/bad differences.

The Unit Tests all pass in unison but one (the one that tests 100 retained messages) and for that, we may need to somehow adjust how the tests execute so they run serially and not within a multi-threaded scenario, which i think is how messages are being lost.

**Comment by chkr1011** [comment]
Hi, I found UnitTest _MqttServer_ConnectionDenied_ which covers exactly the situation you described. So it seems to work properly?

Changing the Interceptors to return a Task is fine. We should also keep the original ones for backward compatibility. 

Before refactoring everything to _async_ please verify that it will gain any benefit. In the past we avoided _await_ in some special cases because the overhead is decreasing the overall performance.

Apart from that your changes are OK so far (without having a deeper look).

**Comment by dealproc** [comment]
@chkr1011 are you game to work with me on finishing this work, so we can include it as part of the v3 package?  If we go the v3 route, we can make breaking changes and not necessarily need to maintain both sync and async versions of the connection validator, etc.

**Comment by chkr1011** [comment]
I close this due to inactivity.
