### ISSUE TITLE
Question: is there a way to receive all retained messages on command?

### ISSUE THREAD

**Issue by dneu** [chkr1011/MQTTnet#520]
I'd like to periodically get all retained messages for a given topic, in order to make sure my data store state is in sync with the MQTT broker status. I want to receive all retained messages on command like I do when I connect and subscribe to a topic.

For instance, if I'm subscribed to topicname/+/+/+, I would like to be able to "flush" all retained messages using the pattern topicname/<serial number>/status/+ and read them all again, without interfering with my original topic subscription.

Is there a way to do that? I'm trying to get retained messages by calling SubscribeAsync again, but it doesn't seem to be re-reading the messages via my ApplicationMessageReceived callback.

**Comment by chkr1011** [comment]
Hi yes there is a method at the server interface. 
You can also add an interceptor (described in Wiki) and do everything you want to.
So you can clear everything (server interface provides a method for it) or clear a subset of retained messages via sending same topic and empty payload.

Best regards
Christian

**Comment by dneu** [comment]
Unfortunately I only have control over the client as we're using CloudMQTT. Is subscribing and unsubscribing the only way? 

If so, do you see any possible pitfalls of the following code?


        public async Task FlushRetainedMessages(string topic)
        {
            await _client.SubscribeAsync(new TopicFilterBuilder()
                .WithTopic(topic)
                .Build());
            await _client.UnsubscribeAsync(topic);
        }

**Comment by dpsenner** [comment]
With the command above I expect your application to end up without a subscription on the topic. Therefore I suppose you intended to first unsubscribe and then subscribe to the topic again, i.e.:

```csharp
    public async Task FlushRetainedMessages(string topic)
    {
        await _client.UnsubscribeAsync(topic);
        await _client.SubscribeAsync(new TopicFilterBuilder()
            .WithTopic(topic)
            .Build());
    }
```

Note that if your application relies on guaranteed message delivery, the above code introduces a race condition. The race causes your application to miss new publishes (even ones with QoS 2) that happen while the application has succeeded the `Unsubscribe` but has not yet completed the `Subscribe`.

Another option is to disconnect your application and then reconnect. This causes the server to send you all the retained messages. This option has another major drawback because it adds another race that causes your application to miss QoS 0 messages.

As far as a i can tell, the best option is to publish a message that causes all other parties to publish their retained messages. This may not be a doable option if the other parties are not available to react on the requested publish.

Distributed systems are a messy place. :-) The best solution essentially depends on the application.

**Comment by SeppPenner** [comment]
I will close this now. Feel free to re-open this if you have some more questions.
