### ISSUE TITLE
Should I combine Collect Data in the Server/Broker or should I use a seperate client

### ISSUE THREAD

**Issue by TheColonel2688** [chkr1011/MQTTnet#528]
I am building a project where I will have dozens of devices sending data to a central server to be collected and stored in a  database.

My question is, should I intercept each message in the server/broker instance using ApplicationMessageReceived event and then store that data from there, or should I have a separate client instance subscribe to the topic and get the data from there?

**Comment by chkr1011** [comment]
Hi,
I recommend the server event because it avoids all the serialization on the same system.

Best regards
Christian

**Comment by dealproc** [comment]
Can you elaborate on this a little more @chkr1011 ... What I'm finding on the server events is that you have to filter the events to see if they are coming from a client, or from the server, before determining what to do with the event, etc.

**Comment by TheColonel2688** [comment]
Yes, @chkr1011 could you elaborate because we would then need to build out our own filtering mechanism.

**Comment by chkr1011** [comment]
Well the question was to either use a dedicated client or the server event handler. Both will work but also for the separate client you need to specify topic to subscribe for. I assume you want to store everything (#). So using the event at the server gives you the same but without an additional client which will serialize and deserialize everything on local machine. You can avoid that overhead when using the server event. And if filtering is needed you have more possibilities because you are not limited to topic filters when using the client.

**Comment by TheColonel2688** [comment]
@chkr1011 Thank you

**Comment by chriswue** [comment]
Unless you want to retain the ability of swapping the MQTT broker out for a different one if the need arises - in which case going for the dedicated client is the way to go.
