### ISSUE TITLE
Can client is not .NET connected to Server?

### ISSUE THREAD

**Issue by JhouXerox** [chkr1011/MQTTnet#585]
Hello,chkr.
MQTTnet is very easy to use.
I've 2 questions yet.

1. I'm using Visual Studio 2017 under windows 7 pro.And I can't see the function like "WithWebsocket".So I can only create a TCP server for the application.
Is it depend on my system?

2.Is there any other way to let the software which is not an .NET application to link the server?
Does the MQTTnet server allow to accept the connection from Objective-C or Android?
If it does,pls tell me how to do that, tnks~

**Comment by chkr1011** [comment]
Hi,
for WebSockets you must build a ASP.NET.Core app for example. MQTTnet.Server is a good example on how to do this. Then MQTTnet can use the WebSocket feature from that application.

You can use Objective-C Android and whatever. The MQTTnet client supports Xamarin but you can also use different MQTT client implementations like PubSubClient for Arduino.

Best regards
Christian

**Comment by JhouXerox** [comment]
Wow,thank you for your answer.

so it's not depends on my system,it's .net core,i get it.

Will it support to create a WebSocket Server by win service or WPF using .net Framework in the future?

**Comment by chkr1011** [comment]
No this will be not supported because WebSockets require a big infrastructure (HTTP server). But ASP.NET Core is already supported well and can be used to add WebSocket functionality to the broker. Also maybe a library like WebSocket4Net can be used to achieve this. You can also add other libraries by just implementing custom server adapters (see factory overloads).

**Comment by JhouXerox** [comment]
Very thank you for your swift reply.
Adapter is the perfect way.
Maybe I'll also try asp.net core later.
Thank you again!
