### ISSUE TITLE
MqttApplicationMessage purpose

### ISSUE THREAD

**Issue by JanEggers** [chkr1011/MQTTnet#589]
HI @chkr1011 im having a look at my perf branch again as im having some spare time.

what is the purpose of MqttApplicationMessage?

im seeing that with mqtt v5 it now conatins a list of userproperties that are useless allocations, even more the whole MqttApplicationMessage is a useless allocation from my point of view.

I rather would like to use the publish packet directly but before changing all the api´s i would like to get your feedback!

**Comment by chkr1011** [comment]
Hi,
the purpose is to hide internals of the MQTT packets from the user. So an ApplicationMessage has no PacketIdentifier nor a dup flag etc. When using the PUBLISH packet directly it would expose that values as well (what I don't like to do).

Maybe we can introduce an interface for application messages. Then there is this regular one when publishing but we can avoid creating it when it comes to receiving and implementing class will be the PUBLISH packet directly. But I am not sure if this is giving any big advantage in CPU or Memory usage.

When it comes to that new user properties you are right. Maybe a solution here is to set them to null by default but also adding support in the message builder so that it will create an instance first if required before setting values.

**Comment by JanEggers** [comment]
I will explore the interface approach and let you know if it yields benifits in perf.

**Comment by chkr1011** [comment]
OK I will then consider changing the defaults for some properties and extend the builder so that we get at least a benefit from this already.
