### ISSUE TITLE
Make IgnorableServerCertificateErrors Configurable

### ISSUE THREAD

**Issue by asebak** [chkr1011/MQTTnet#59]
Any way to make the IgnorableServerCertificateErrors configurable.  I needed  a way to add one but couldn't do so.

Right now it's harded coded with the following:

                    _socket.Control.IgnorableServerCertificateErrors.Add(ChainValidationResult.IncompleteChain);
                    _socket.Control.IgnorableServerCertificateErrors.Add(ChainValidationResult.RevocationInformationMissing);

**Comment by chkr1011** [comment]
Hi,
please have a look at the _develop_ branch. The next version has more options. But it is still not possible to add own because the implementations are different per platform.

Please let me know if you need further options as in _develop_. The next version will be released soon.

Best regards
Christian

**Comment by asebak** [comment]
Yeah it looks like you added more, the specific one I needed was ChainValidationResult.InvalidName

**Comment by chkr1011** [comment]
I also added a callback mechanism for dealing with complex certificate validations. It is described in the wiki. I will close this ticket. Please let me know it you need more features to deal with certificates.

Best regards
Christian
