### ISSUE TITLE
Binary user password

### ISSUE THREAD

**Issue by jimsch** [chkr1011/MQTTnet#640]
I am expecting to use a binary not a text based password.  How can I do authentication with a non-text based password

**Comment by chkr1011** [comment]
Hi,
this is not possible because the password is usually a string. This comes from the MQTT specification.
But when using MQTT5 you can use the extended authentication data instead.

Or you just convert your binary password into a base64 string first before sending and then you can check this string.

Best regards
Christian

**Comment by jimsch** [comment]
Ok - I will agree that this is the normal practice.  I would disagree that this is coming from the MQTT specification unless it is something that changed before version 3.1.1.  Where are you seeing this in the spec?

**Comment by chkr1011** [comment]
It seems that this was wrong since the very first version of MQTTnet. 😨 
I changed this so that you set and read the password as a byte array. This change is backward compatible (when using the builders).

**Comment by chkr1011** [comment]
I released a new nuget _3.0.3-rc2_. The password is now a byte array. But the options builder still supports strings.
