### ISSUE TITLE
Client Connection Validator does not expose the connect properties

### ISSUE THREAD

**Issue by jimsch** [chkr1011/MQTTnet#657]
I need to get to the connect properties during authentication - specifically the authentication method and data fields, but other items such as user properties could also be needed.

At some point in the future I may also want to get to the actual packet bytes so you might want to keep that in mind.

**Comment by jimsch** [comment]
I will also need to send responses back async during the connector validator.  Does this mean that I need to have the clientAdapter passed in as well?

**Comment by jimsch** [comment]
An alternative to doing a conversation during the callback to the connector validator would be to allow for a return value which will not send a CONNACT, but setup the session and allow for an AUTH message to be returned instead.

**Comment by chkr1011** [comment]
Hi,
please create separate tickets for separate things. Otherwise I close one which is done and then everything else gets lost.

I agree that lots of properties are missing in the context. I will add such of them in 3.0.3 but I cannot give you the packet bytes directly. There is no need in my opinion. This library should do all that annoying work four you.

Sending an AUTH packet while connecting is not yet supported. No other message can be sent/received at the moment. Fully (or at least most) support for MQTTv5 at server side will be implemented in v3.1.x of this library which may be released by end of this year.

I also add some properties to the context which are later forwarded to the CONNACK packet. I hope that helps to solve that issues.

Best regards
Christian

**Comment by jimsch** [comment]
OK - If you don't support doing AUTH messages yet then I guess I might need to skip using this library.  I am looking at implementing https://datatracker.ietf.org/doc/draft-ietf-ace-mqtt-tls-profile/ which is currently better defined for V5 than for V3.x.

**Comment by chkr1011** [comment]
Yes then you must skip this library for now. The problem is that the message handling has to be rewritten in order to support that and I assume I will not be able to do that before end of 2019.
