### ISSUE TITLE
Can I help you guys with the project?

### ISSUE THREAD

**Issue by SeppPenner** [chkr1011/MQTTnet#667]
@chkr1011 and @JanEggers: I could help you with this project, if you like.

Steps, I would certainly do:

* Sort the issues to topics (Tags)
* Close issues where no (or less) logging information is provided or where it's unclear of what the user asks.
* Add a new timeline to the project (Using correct milestones): Check https://github.com/chkr1011/MQTTnet/milestones, latest version was 2.7.4.
* Check and merge valid pull requests if there are some
* Check and work on issues and feature requests if desired (With possible discussion if they're really needed)

If you need some references:
* My profile with all the stuff I've previously done: https://github.com/SeppPenner?tab=repositories
* I've worked on the German translation of the Arduino command reference: https://github.com/arduino/reference-de
* I've added a fork of a [Serilog](https://serilog.net/) sink for PostgreSQL (That has some new features and is better maintained): https://github.com/SeppPenner/SerilogSinkForPostgreSQL
* I've created a new [Serilog](https://serilog.net/)  sink for Amazon S3: https://github.com/SeppPenner/Serilog.Sinks.AmazonS3
* I've provided some more nuget packages (Check https://www.nuget.org/packages?q=HaemmerElectronics.SeppPenner) and some more projects can be found on my repository page.

Finally, why do you need me:

* To be honest, I do not know, who exactly is an active developer here (I assume only the two of you mentioned above)
* The issues are growing and growing and sometimes do not seem to get the neccessary attention
* I've already worked on several open source projects on my own and in teams as shown above
* I'm a .Net developer with focus on WPF and Asp.Net (or .Net Core) in general with about 4 years of experience right now
* One more person working on this can help you to manage the project better (I also assume that you guys have some hobbies and family, etc. 😄)
* It's quite impossible for one or two people to manage a project like this with more than 200000 downloads from nuget
* I'm from Germany as well as @chkr1011 :)

**Comment by JanEggers** [comment]
moin, hier ist auch nen Fischkopf :)

from my point of view help is always welcome. 

> The issues are growing and growing and sometimes do not seem to get the neccessary attention

Maybe that is a good starting point to provide some pullrequests. 

In the end @chkr1011 has to decide has he started this project.

**Comment by SeppPenner** [comment]
> moin, hier ist auch nen Fischkopf :)

Hab ich mir anhand des Names fast schon gedacht ;)

> In the end @chkr1011 has to decide has he started this project.

Okay, I will see what I can do here.

**Comment by chkr1011** [comment]
Hi @SeppPenner,

sure, help is welcome! As you already saw there is no time left for maintaining milestones, keeping the Wiki up to date all the time and responding to tickets.

Please let me know what you are interested in. Docs, new features, bug fixing? Or just everything? I can give you some things if you want and don't know yet where to start.

Your projects looking promising (not checked all of them in detail) 😄 

Here are a few things which are important:
1. The library should support at least .net 4.5.2 as this is still supported by MS. So moving to .net standard only etc. is not an option (yet).
2. The existing code defines the code style. But there are no big special things. It is just the default .net coding standard style. Maybe some minor changes here and there.
3. I will release every version on my own. So I am the only one which has the keys for nuget etc. 😄 
4. It is important to NOT include some code from other projects which may have different license etc.

Current "Roadmap":
**3.0**.x covers mostly MQTTv5 features and bug fixes. The server is compatible with MQTTv5 packets but does not implement new MQTTv5 features.
**3.1**.x should cover must of MQTTv5 features on server side (but not all in the first run).

Beside that there is the standalone _MQTTnet.Server_ which is similar to _mosquitto_ broker but with scripting functionality in Python. This server can be also deployed as an Azure Web Server. Whenever a new nuget is generated the server is also updated because it is the reference implementation of a server and can be also used for testing.

Open topics:
* Rewrite of the topic comparer using Span etc. and get rid of the "copied" code from other project. 
* Writing proper docs for MQTTnet.Server at the Wiki.
* Adding more samples for client, server etc.
* Compare performance with Pipelines and adopt if it gives enough benefit (respecting support for 4.5.2).
* Creating template for issues (so that people at least provide **FULL** sample code to reproduce or better create/modify a UnitTest etc.)

I also added the room "devs" in gitter. There we can also discuss topics without having an issue for everything.

That's it. If you want you can start with something you want. Just create tickets for that or create pull requests. We will see how it goes then. 

Best regards and willkommen an Board 🎉 
Christian

**Comment by SeppPenner** [comment]
> Docs, new features, bug fixing?

I'm interested in everything but would start with organizing the project. I have already peaked at the code when trying to add some options for https://github.com/chkr1011/MQTTnet/issues/664 (But I failed 😄).

>* The library should support at least .net 4.5.2 as this is still supported by MS. So moving to .net standard only etc. is not an option (yet).
> * The existing code defines the code style. But there are no big special things. It is just the default .net coding standard style. Maybe some minor changes here and there.
> * I will release every version on my own. So I am the only one which has the keys for nuget etc. 😄
> * It is important to NOT include some code from other projects which may have different license etc.

I'm fine with the guidelines. And of course, it's your project, meaning your rules ;)

I guess, I will start with some documentation tasks:

* Writing proper docs for MQTTnet.Server at the Wiki.
* Adding more samples for client, server etc.
* Creating template for issues (so that people at least provide FULL sample code to reproduce or better create/modify a UnitTest etc.)

> I also added the room "devs" in gitter. There we can also discuss topics without having an issue for everything.

Ok, I will check this out, too 👍

**Comment by chkr1011** [comment]
OK perfect 😄
