### ISSUE TITLE
MQTTnet.Server understanding

### ISSUE THREAD

**Issue by FrancescoLusetti** [chkr1011/MQTTnet#676]
I'm trying to study the MQTTnet.Server but I don't know Python
Could you simply explain what is used for?

**Comment by FrancescoLusetti** [comment]
And even if it could be removed easily to reduce the work on the server if it's not needed

**Comment by chkr1011** [comment]
Hi,
Python scripts are supported to build simple business logic for in the server or checking client credentials without the need of a predefined file format etc.

It just has a very small performance impact because these scripts are all compiled into IL code.

If you don't need it you should start with your own server implementation because otherwise you have a MQTT server which does not validate any client connection. There is no other way of doing that apart from implementing the proper Python function.

Best regards
Christian

**Comment by FrancescoLusetti** [comment]
Thank you.
Because I need only an API to give credential to access and an id for the client ID other than the MQTT server

**Comment by SeppPenner** [comment]
> Because I need only an API to give credential to access and an id for the client ID other than the MQTT server

Do you have an example for this? I don't get it...

**Comment by chkr1011** [comment]
Such API don't exist (Configuring credentials). The reason is that this is that there are different use cases. Sometimes people only want to have user+pass and sometimes clientid+user+pass.

But dealing with Python is not a big thing. Replacing && with _and_ and || _or_ and braces with indents should be done by anyone. There is also some sample code in the sample script. You just have to rewrite this.

**Comment by SeppPenner** [comment]
@chkr1011 As this is already the second (or third) question for this API topic: I guess, I will try to build one API in an example project soon and provide it in the wiki...

**Comment by chkr1011** [comment]
Yes that would be amazing.

**Comment by chkr1011** [comment]
Are here any updates or drafts? I can see from GitHub statistics that MQTTnet.Server gets more and more attention and is being downloaded quite often now. 

If there is no draft already etc. I can also try to create something quickly.

**Comment by SeppPenner** [comment]
I wanted to create a draft on this but I got previously stuck on the other topics (E.g. the examples with the managament of subscriptions / user topic restrictions and that stuff). It's now finished and I hope that there is some time this weekend to check the other issues here and provide something.

**Comment by SeppPenner** [comment]
I have done this in https://github.com/chkr1011/MQTTnet/wiki/Examples (Respective https://github.com/SeppPenner/NetCoreMQTTExampleIdentityConfig). This doesn't work properly yet (At least not to start the broker and the API at the same time), but I will update it if I get a clue what's wrong.
