### ISSUE TITLE
Provide the option to get the username and used password in WithSubscriptionInterceptor() and WithApplicationMessageInterceptor().

### ISSUE THREAD

**Issue by SeppPenner** [chkr1011/MQTTnet#682]
This is needed for https://github.com/chkr1011/MQTTnet/issues/664 and https://github.com/chkr1011/MQTTnet/issues/668: 
> With one set of user and pass ANY client ID can be used.

Currently, these functions only return the client id. If my project (https://github.com/SeppPenner/NetCoreMQTTExampleJsonConfig) should use the username and password on subscription or publish, I don't know how to do this in another way. Any suggestions, @chkr1011?

**Comment by chkr1011** [comment]
Hi,
the problem is that this data is not correlated. So the data you need was only part of the initial CONNECT packet. So the requested data must be kept and forwarded to later subscription contexts.

As far as I can see this is no trivial change. I will try to find a solution.

Best regards
Christian

**Comment by SeppPenner** [comment]
> As far as I can see this is no trivial change. I will try to find a solution.

That's what I was afraid of :D

**Comment by JanEggers** [comment]
I think it should be easy let me have a look at it,

**Comment by JanEggers** [comment]
I exposed the complete connect packet that way a user can use the credentials, clientid, wether its a tls connection or some other information provided with the mqtt v5 user properties

**Comment by chkr1011** [comment]
I made this change in the newest commit on develop. I am not very happy with it because it seems to be a little bit hacky.

**Comment by chkr1011** [comment]
I changed this again and now it is perfect (in my humble opinion) 😄

**Comment by chkr1011** [comment]
Now there is a dictionary available in the session object. This works similar as in ASP.NET. This items dictionary is exposed in all interceptors and validators. So you can now "move" data from the initial connect like the username or password to that dictionary. When interception an application message etc. you can read your value from that dictionary and use it. This also allows much more things than exposing the username and password hard coded.

You can for example query access rights upon connect and store the access rights in the session items. When subscribing you only need to read that from the items instead of loading it from a slow source like a file, DB etc.

I also exposed that to MQTTnet.Server. So the session items are also exposed to Python Scripts and can be used the as well.

**Comment by chkr1011** [comment]
Now there is a dictionary available in the session object. This works similar as in ASP.NET. This items dictionary is exposed in all interceptors and validators. So you can now "move" data from the initial connect like the username or password to that dictionary. When interception an application message etc. you can read your value from that dictionary and use it. This also allows much more things than exposing the username and password hard coded.

You can for example query access rights upon connect and store the access rights in the session items. When subscribing you only need to read that from the items instead of loading it from a slow source like a file, DB etc.

I also exposed that to MQTTnet.Server. So the session items are also exposed to Python Scripts and can be used the as well.

**Comment by SeppPenner** [comment]
I will try this and build it into the example projects.

**Comment by SeppPenner** [comment]
I can confirm that this works as expected in the latest beta version.
