### ISSUE TITLE
Multithreading question with MqttClient

### ISSUE THREAD

**Issue by agrath** [chkr1011/MQTTnet#684]
I just wanted to clarify behaviour with UseApplicationMessageReceivedHandler on MqttClient (non managed)

If you have a broker (I'm using mosquito under ubuntu on a remote server) which is receiving many publishes from different clients on multiple topics (IOT style, like /devices/{macaddress}/{measurement}) and the MqttClient has a single subscription on /devices/+/# can I expect that UseApplicationMessageReceivedHandler will be called single threaded or do I need to maintain thread safety within this event handler?
This may come down to the implementation of the broker itself but I would expect that there is a single TCP connection between the MqttClient (on the subscribe end) and the broker so the likelihood is that there is no need to be thread-safe with my current usage.
Can you confirm?

**Comment by chkr1011** [comment]
Hi,
I don't get exactly what you mean because thread safe means that the resource you are CALLING supports multiple threads. But when receiving messages this does not apply. I cannot answer if the resources you are CALLING are thread safe or not. This MQTT is not (when it comes to publishing, connecting etc.). Access to it should be locked all the time or done by one thread only (which I would prefer).

When it comes to message ordering and internal use of threads in the client the answer is: There is only one thread which is listening on the TCP connection (yes there is only one). So your messages are processed in order and NOT in parallel. If you need that for example you should use _Task.Run_ or a dedicated queue with worker threads or whatever you need.

It is also not relevant what is subscribed and in which order or using a filter or a full unique topic. All messages are processed by the same thread in the order as they are sent by the server (broker).

Does this confirm your question?
Best regards
Christian

**Comment by agrath** [comment]
@chkr1011 thank you, you understood my poorly worded question correctly.
By thread safe, I meant within the event handler, did I need to be aware of thread safety of other objects I was interacting with - to which, the answer is no. Since it will never be called in a parallel, as long as other objects in the scope of the event handler are only ever called by that event handler then I don't need to worry about this.
Your answers are exactly what I needed to know, thank you.
