### ISSUE TITLE
connection refused on android

### ISSUE THREAD

**Issue by reiterasrls** [chkr1011/MQTTnet#690]
Hi,i'm using mqttnet in xamarin forms project (android and uwp) as a server and xamarin forms android as a client.
Id i run server on uwp app it work well but if i run android server client receive connection refused from server.
can you help me to resolve it
I see that the problem is to start broker on android because return exception (access denied).
It' s possibile to not work broker on Android?

**Comment by chkr1011** [comment]
Did you gave the app the proper permissions? Maybe opening a server (port) requires additional permissions.

**Comment by reiterasrls** [comment]
i gave interner permission and network state and installed mqttnet in android project too. 
my code is sample 
 Task.Factory.StartNew(async () =>
            {
                var optionsBuilder = new MqttServerOptionsBuilder()
               .WithConnectionBacklog(100)
               .WithDefaultEndpointPort(1883);
                var mqttServer = new MqttFactory().CreateMqttServer();
                await mqttServer.StartAsync(optionsBuilder.Build());
            });
i have removed await and used continuewith to have exception. Result is Set socket option exception

**Comment by denisgeom** [comment]
I had the same problem on BeagleBoardx15 running Linux Debian
I found out the problem is in the method MqttTcpServerListener::Start( ...)
The call to  _socket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.NoDelay, true);
generate an exception access denied.
It seems it should be SocketOptionLevel.Tcp instead of SocketOptionLevel.Socket
change to:  _socket.SetSocketOption(SocketOptionLevel.Tcp, SocketOptionName.NoDelay, true);
After modifying this the server works.

**Comment by SeppPenner** [comment]
@denisgeom Okay, this is interesting...

**Comment by reiterasrls** [comment]
@denisgeom thanks. one question...it's possibile set your code in library without modify source code?
I don't know the library well

**Comment by chkr1011** [comment]
@reiterasrls At the moment you can set _NoDelay_ to _false_ in the MQTT Server options. Then the failing method is not called.

@denisgeom Are you sure that your mentioned solution is correct? I am not sure what the difference in using TCP instead of Socket as the parameter is. All examples I found are using the Socket parameter.

**Comment by denisgeom** [comment]
I am guessing, since you open the socket as TCP, you may only change socket option for TCP.

Leaving, SocketOptionLevel.Socket will generate access denied exception.
As soon as I changed it to SocketOptionLevel.Tcp
no more exception and server works.
This only apply to linux, I also ran the code without any change in Windows and running in Windows I did not have this issue. I also targeted .net core 2.2 and change the debug symbol to portable. As of now, they were all set for windows, and could not debug under Linux.
So my guess is the code was never run under Linux, or Android and issue was not noticed since it works fine under Windows.
Anyway, this code should have fail or work on both OS without any change, so something is different in the underlying code. Linux, seems to be more strict on what you can access.

**Comment by chkr1011** [comment]
You are right. I found this: https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.setsocketoption?view=netframework-4.8 

There TCP is used for NoDelay...

**Comment by reiterasrls** [comment]
thank you all
the problem remains and can be solved by changing the source code ... right?

**Comment by chkr1011** [comment]
Please try the latest beta I released yesterday. It contains a fix.

**Comment by denisgeom** [comment]
I did try the latest NuGet package 3.0.6-beta1 and it does not crash anymore when opening the server on Linux and Windows

**Comment by reiterasrls** [comment]
I try it and let you know, thanks for all

**Comment by reiterasrls** [comment]
i have tried beta release. now with the same code i have socket exception "address already in use" ever

**Comment by chkr1011** [comment]
Let me try to build a small Xamarin sample. I never had the use case that a smartphone is the server...

**Comment by chkr1011** [comment]
After doing some research I found that the default bound IP address is not supported in Android. So you have to use the actual address of the device. 

```csharp
IPHostEntry ipHostInfo = Dns.GetHostEntry(Dns.GetHostName());
IPAddress ipAddress = ipHostInfo.AddressList[0];

var server = new MqttFactory().CreateMqttServer();
server.StartAsync(new MqttServerOptionsBuilder()
    .WithDefaultEndpointBoundIPAddress(ipAddress)
    .WithDefaultEndpointBoundIPV6Address(IPAddress.None)
    .Build()).GetAwaiter().GetResult();
```
But I recommend to do some more research in order to better understanding of the implications.

**Comment by reiterasrls** [comment]
thanks...try it and inspet eventually problems

**Comment by chkr1011** [comment]
@reiterasrls Please reopen the ticket if you experience problems.

@SeppPenner Do you think the above snipped is a good thing for the Wiki?

**Comment by SeppPenner** [comment]
Yeah, that is a good idea. I will add this soon.

**Comment by SeppPenner** [comment]
It's here: https://github.com/chkr1011/MQTTnet/wiki/Server#special-notice-for-using-the-server-project-in-android and there: https://github.com/chkr1011/MQTTnet/wiki/Tips-and-Tricks#special-notice-for-using-the-server-project-in-android

**Comment by ozersenol** [comment]
@chkr1011 I tried it but it is not working. IP return 127.0.0.1 with this example. I dont know it as it should be? I also tried real device ip and did not work. could you please check my request #1960 ? Thanks.
