### ISSUE TITLE
Reprocess messages if an error happens

### ISSUE THREAD

**Issue by det-iot** [chkr1011/MQTTnet#714]
Hello,

I would like to know which would be the best way to do the following using mqttnet.

I have a subscriber which each time the UseApplicationMessageReceivedHandler fires, the message is sended to other place.

If the method which send the message fail, How could I reprocess this message and try to send it again?

This could also happend If I want to republish the message that subscriber have received. If the publisher fail, how should I reprocess the message to publish it again?

------------------------------

A little of code which handled the subscriber:

```
 mqttClient.UseApplicationMessageReceivedHandler(async e =>
                {
                   try
                    {
                        await SentToDestination(DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ssZ") + ";" + e.ApplicationMessage.Topic + ";" + Encoding.UTF8.GetString(e.ApplicationMessage.Payload) + Environment.NewLine);
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine("Error" + ex);
                        throw;
                    }
                });
```

Thank you.

### Which project is your bug related to?
- [x] Client
- [ ] ManagedClient
- [ ] MQTTnet.Server standalone
- [ ] Server
- [ ] Generic

**Comment by chkr1011** [comment]
Hi,
I would recommend creating your own messages for this. Probably some JSON in the payload. Then you can handle messages using some correlation IDs and some dedicated response topics. So a full message is sent for a request and a full one for the response. If no response happens or the response contains an error you can try again.

Don't make use of the QoS because it is only intended for the message in general. So any subsequent business logic should be part of it. If it is just a small thing like writing the message to a storage it might be OK. But having huge business logic may lead to dead locks etc.

Please checkout the RPC extension. There you can see how to build request/response with custom topics and a TaskCompletionSource etc.

I hope that helps.

Best regards
Chrsitian
