### ISSUE TITLE
Suggestion: Remove Exception in MQTTnet.Client.ConnectAsync change to return value

### ISSUE THREAD

**Issue by XingJordan** [chkr1011/MQTTnet#722]
Hi,
currently I'm implementing a Client with MQTTNet.
related to this issue:
https://github.com/chkr1011/MQTTnet/issues/249

I would disagree that an exception has to be thrown if the server is unreachable at the point 
Client.ConnectAsync is called.

From my point of view it would be advantagous if the exception is removed again and a proper return value is added to the ResultCode field of the MqttClientAuthenticateResult.

What's the purpose of this exception, what is your code supposed to do with the exception?
A return value can be handled more easily and does not add extra try catch to your code.

Anyway ConnectAsync runs in the background and tries to connect all the time even if exception is thrown all the time.

For handling of successful connection the API already offers Handlers like 
- HandleConnectedAsync
- HandleDisconnectedAsync

So I would be happy to start discussion with you about this point.
Best,
    Mathias

**Comment by SeppPenner** [comment]
Well, what's the problem with adding a `try-catch`? I mean, I can understand the idea behind your argumentation but is it really neccessary to change this?

@chkr1011 What do you think?

**Comment by det-iot** [comment]
Hello,

I was opening other ticket but I think it could be related to this.

I tried to connect to a broker with something like this:

```
            try
            {
                conectadoSuscriptor = await mqttClientPublisher.ConnectAsync(optionsPublisher);
            }
            catch (Exception)
            {
                Console.WriteLine("Error al conectar al publicador");
            }
```

After that I would need to test if the connection  was successfully or not:

```
if (conectadoSuscriptor.ResultCode == MQTTnet.Client.Connecting.MqttClientConnectResultCode.Success)
            {
             <...>
            }
```

The problem here is that even if the connection fail, the value of conectadoSuscriptor.ResultCode was Success.

So I have to created a boolean var to know if the connection was successfully or not

```
            try
            {
                await mqttClientSubscriber.ConnectAsync(optionsSubscriber);
                conectadoSuscriptor = true;
            }
            catch (Exception)
            {
                Console.WriteLine("Error al conectar al suscriptor");
                conectadoSuscriptor = false;
            }
```

**Comment by chkr1011** [comment]
Hi,
thank you for sharing your ideas. In my opinion you are mixing to different things here. Let me explain..

If would rather not replace the exception because otherwise you loose a lot of information. The exception usually has some inner exception with more details. For example the _SocketException_ which has an error code etc. This gives more details about the error like "No such host is known" or "Connection forcibly closed" or whatever. Removing the exception will hide those details. And this is not an option for me. Same applies when using different or custom transport implementations (WebSockets etc.). They may have more or different information.

Another thing is that even .net behaves the same. There is an exception thrown when using the socket. And we cannot avoid them. So anyone has to catch them anyways (we cannot avoid them in order to speed up performance). 

The fact the you get a success is another story. Because of the nature of enum this is _Success_ by default. But how to you get it? You cannot have an instance of _MqttClientAuthenticateResult_ because you got an exception instead. Please provide a full snipped to that I can understand why you have _Success_ where it comes from.

Best regards
Christian

**Comment by JanEggers** [comment]
Id rather go the other way and remove the return value of connect. so it either succeeds or throws an exception with the code that is now in the response.

for me it is differcult if transport errors are handled with exceptions and mqtt auth errors are handled with return value.

**Comment by det-iot** [comment]
@chkr1011 due I'm not able to use the "success" result, I have used the following structure:

```
        public async Task ManageMQTTClient(MQTTConfiguration MQTTconfigSubscriber, MQTTConfiguration MQTTconfigPublisher)
        {
            bool conectadoPublicador = false;
            bool conectadoSuscriptor = false;

            try
            {
                IMqttClientOptions optionsSubscriber = new MqttClientOptionsBuilder().<...>

                IMqttClient mqttClientSubscriber = new MqttFactory().CreateMqttClient();

                IMqttClientOptions optionsPublisher = new MqttClientOptionsBuilder().<...>

                IMqttClient mqttClientPublisher = new MqttFactory().CreateMqttClient();

                mqttClientPublisher.UseDisconnectedHandler(async e =>
                    {
                        await Task.Delay(TimeSpan.FromSeconds(10));
                        try
                        {
                            await mqttClientPublisher.ConnectAsync(optionsPublisher);
                            if (mqttClientPublisher.IsConnected)
                            {
                                conectadoPublicador = true;
                            }
                            else
                            {
                                conectadoPublicador = false;
                            }
                        }
                        catch
                        {
                            conectadoPublicador = false;
                        }
                    });

                mqttClientSubscriber.UseDisconnectedHandler(async e =>
                    {
                        await Task.Delay(TimeSpan.FromSeconds(10));
                        try
                        {
                            await mqttClientSubscriber.ConnectAsync(optionsSubscriber);
                            if (mqttClientSubscriber.IsConnected)
                            {
                                conectadoSuscriptor = true;
                            }
                            else
                            {
                                conectadoSuscriptor = false;
                            }
                        }
                        catch
                        {
                            conectadoSuscriptor = false;
                        }
                    });

                mqttClientSubscriber.UseApplicationMessageReceivedHandler(async e =>
                {
                    if (conectadoPublicador)
                    {
                        try
                        {
                            await mqttClientPublisher.PublishAsync(...);
                        }
                        catch (Exception ex)
                        {
                            Console.WriteLine<...>
                        }
                    }
                    if (conectadoPublicador == false)
                    {
                        Console.WriteLine<...>
                    }

                    try
                    {
                        SendToOtherOutput<...>
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine<...>
                    }
                });

                try
                {
                    await mqttClientPublisher.ConnectAsync(optionsPublisher);
                    conectadoPublicador = true;
                }
                catch (Exception)
                {
                    conectadoPublicador = false;
                }
                try
                {
                    await mqttClientSubscriber.ConnectAsync(optionsSubscriber);
                    conectadoSuscriptor = true;
                }
                catch (Exception)
                {
                    conectadoSuscriptor = false;
                }
                if (conectadoSuscriptor)
                {
                    try
                    {
                        await mqttClientSubscriber.SubscribeAsync(<...>)
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine<...>
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine<...>
                throw;
            }
        }
```

But I would like to use `MQTTnet.Client.Connecting.MqttClientConnectResultCode.Success)` instead of creating a boolean var to know if the connection was establish successfully

**Comment by chkr1011** [comment]
@JanEggers I agree that having exceptions only makes more sense. But then this also applies for publish, subscribe etc. This also may comes with a performance downgrade etc. 

At the moment I don't want to change the APIs and on the other hand the received MQTT packet is somewhat of a success. If someone prefers exceptions it is no big deal to throw on MQTT exceptions which are deriving from our exceptions. With that approach everyone can use the way the want's to.

**Comment by chkr1011** [comment]
@det-iot I recommend to create your own MQTT client class and throw some custom exceptions. 

I usually call Subscribe directly after Connect. If the connect fails the Subscribe method will be never called. If the client connects but the server disconnects it (due to "no success") the client is closed and subscribe will also fail due to a not connected client. But as I said I would add an abstraction layer where you throw exceptions in a way you want / need.

**Comment by det-iot** [comment]
@chkr1011  Thank you for your comments

**Comment by SeppPenner** [comment]
I guess this can be closed as well.
