### ISSUE TITLE
Add the auto-reconnect functionality to the regular client.

### ISSUE THREAD

**Issue by SeppPenner** [chkr1011/MQTTnet#724]
I don't know if it is a good idea but is it possible to add the auto-reconnect to the regular client as well (It's already available in the ManagedClient)?

Which project is your feature request related to?

- [x] Client

**Comment by chkr1011** [comment]
Hi,
I don't want to move it there because the regular Client is mostly passive. The reason is that anyone has different rules. So some times the delay is different or increases over time or there is a backup server which should be tried after the primary one failed or different password shall be used etc. etc.

The _ManagedClient_ is just one way to handle that. It only covers the most basic things.

If you want to reconnect easily, you can put _ConnectAsync_ in the handler of the _Disconnected_ event. That is just one line 😄 

Why do you want to add it? Is there any other reason?

Best regards
Christian

**Comment by SeppPenner** [comment]
> If you want to reconnect easily, you can put ConnectAsync in the handler of the Disconnected event. That is just one line 😄

I know. If I read the wiki correctly before, I wouldn't have run into the issue that my delay didn't work:
I was trying to do a `ConnectAsync` in the `DisconnectedHandler`. Afterwards, I had a `Task.Delay(...)`.
The funny thing was that the delay didn't work properly because the `ConnectAsync` throws the `Disconnected` event every time the reconnect failed. 😄

Reading the wiki helps sometimes:
> The event is also fired if a call to ConnectAsync has failed because the server is not reachable etc.

My code was something like:

```csharp
mqttClient.DisconnectedHandler = new MqttClientDisconnectedHandlerDelegate(OnDisconnected);

// ....

private async Task OnDisconnected(MqttClientDisconnectedEventArgs e)
{
    await mqttClient.ConnectAsync(options, CancellationToken.None));
    await Task.Delay(TimeSpan.FromSeconds(5));
}
```

Changing the code to this:

```csharp
mqttClient.DisconnectedHandler = new MqttClientDisconnectedHandlerDelegate(OnDisconnected);

// ....

private async Task OnDisconnected(MqttClientDisconnectedEventArgs e)
{
    await Task.Delay(TimeSpan.FromSeconds(5));
    await mqttClient.ConnectAsync(options, CancellationToken.None));
}
```

works, of course 😄

This was some stupid mistake I made today. Glad that I had the time to test the disconnecting procedure properly :)
