### ISSUE TITLE
ManagedClient reconnect receive all message

### ISSUE THREAD

**Issue by reiterasrls** [chkr1011/MQTTnet#749]
Hi, one problem.
I using managedclient on android device.
when i close app and  reopen, it receives again all the messages even those already received.
It's normal behavior?

**Comment by SeppPenner** [comment]
I assume, you're using the latest version? For me, this looks like you don't set the clean session flag (Check e.g. https://www.hivemq.com/blog/mqtt-essentials-part-7-persistent-session-queuing-messages/) or send messages as retained messages (Check e.g. https://www.hivemq.com/blog/mqtt-essentials-part-8-retained-messages/).

Another thing: It would be good if you provide a small code example to validate that there are no other issues causing this behaviour.

**Comment by reiterasrls** [comment]
you are right. i used retainflag to publish message.
but if I only want to receive messages after the connection is broken?

**Comment by SeppPenner** [comment]
I don't think it's possible to only get some of the messages with this setup.

There are two ways to get what you want I would say:

* Retain the messages you want to get and use `cleansession = true` to clear the other messages from the session.
* Recieve all messages when reconnecting and validate them in the app (Storing all messages will probably be not an option, but maybe storing the last 3 timestamps or so might be, depending on your use case)

You can find an overview of the different scenarios e.g. [here](http://www.steves-internet-guide.com/mqtt-clean-sessions-example/)

@chkr1011 Please correct me if I'm wrong.

**Comment by reiterasrls** [comment]
store message is not my preferred solution because devices are not io performance.
I will follow hybrid solution..stop broken messages and check connectivity status and after reconnect send tcp (or http) request to resync state.
you think if it is a possible solution?

**Comment by SeppPenner** [comment]
> store message is not my preferred solution because devices are not io performance.
I will follow hybrid solution..stop broken messages and check connectivity status and after reconnect send tcp (or http) request to resync state.
you think if it is a possible solution?

This depends on your use case and the data you want to exchange. In general, this should be a possible solution.

It's just difficult for us to help you out if we don't have a context or some examples. That's why I will close this issue for now. Feel free to ask futher questions related to the `MQTTnet` project if there are more.
