### ISSUE TITLE
ManagedMqttClient - IMqttClientOptions - readOnly - Reconnection

### ISSUE THREAD

**Issue by JTrotta** [chkr1011/MQTTnet#78]
Hello,
I need to set the password during each connection. I'm using a OTP psw with my broker.
Is it possible to expose a method to calculate the password at each re connection? 
JJ

**Comment by chkr1011** [comment]
I assume you can hold a reference of the options in your code. In the disconnect event you can manipulate the password because it has a setter. Then the client will use that password for the next connect. Another solution is not yet implemented.

**Comment by JTrotta** [comment]
I suppose I can't do that:
Interface properties are read only
`    public interface IMqttClientOptions
    {
        bool CleanSession { get; }
        string ClientId { get; }
        TimeSpan DefaultCommunicationTimeout { get; }
        TimeSpan KeepAlivePeriod { get; }
        string Password { get; set; }
        MqttProtocolVersion ProtocolVersion { get; }
        MqttClientTlsOptions TlsOptions { get; }
        string UserName { get; }
        MqttApplicationMessage WillMessage { get; }
    }`
On the other hand, I found a working solution adding a property into ManagedMqttClientOptions:
`DynamicPassword = new GetDynamicPassword(_encryptionService)`

May I add a PR or you prefer some lines of code?
JJ

**Comment by chkr1011** [comment]
You have to use the implementation. The interface only has a getter.  Then you can use the setter as well.
I think your implementation should be at your code because it is a very special use case. Also because now there are two password fields. This is more confusing in my opinion. Let me know if it works if you use the implementation instead of the interface. If not we can try to find a solution which is not that special. If you need assistance I can also write a small demo.

**Comment by JTrotta** [comment]
You mean to cast it? 
I'm using:
`_mqttOptions = new ManagedMqttClientOptions();
            _mqttOptions.ClientOptions = new MqttClientTcpOptions()
            {                
                CleanSession = true,
                ClientId = "XX",
                DefaultCommunicationTimeout = TimeSpan.FromSeconds(20),
                KeepAlivePeriod = TimeSpan.FromSeconds(31),
                Port = _communicationSettings.MQTTUseCertificates ? 8883 : 1883,
                Server = _communicationSettings.MQTTBrokerEndPointIP,
                UserName = _communicationSettings.MQTTUserName,
            };`

But `_mqttOptions.ClientOptions` is an interface. The only way is to cast it during disconnect.
Moreover, It's a good practice to wait some seconds before re connection (i.e. `AutoReconnectDelay = TimeSpan.FromSeconds(10)` ). This means that the TOTP password could be not aligned with the server one.
Anyway I do not think it's confusing: we can have a static Password (for default and standard use) and a DynamicPassword (self explaining, but we can add hints) to be used only if needed. 
IMHO, it could be a good feature, nobody has it.
I did some test and it's working good with your Autoreconnect Task.

Let me know.
JJ

**Comment by chkr1011** [comment]
Ah you are using the _ManagedClient_. OK that is a different story. 

Maybe a good idea which is simpler is adding a function to the _ManagedClient_ options. A new property called "PasswordProvider" and of type Func<ManagedClientOptions, string>. If that is <null> the client will use the plain password from the inner options. Otherwise it will call that method and provides the options (may needed for generation etc.). I assume this support your use case. What do you think?

**Comment by JTrotta** [comment]
You got it. Yes that's the solution.
I already did that, and it works good.
Let me know if you need a PR or you want to do it by yourself.

Thank you Christian!

**Comment by chkr1011** [comment]
You can always create a pull request if you like. I will review it in the afternoon. If changes are required we can discuss them together.

**Comment by chkr1011** [comment]
@JTrotta Please have a look at the _develop_ branch. I implemented a new class for credentials. In the test code you can find an example how to use a changing password. I hope this fits your needs. It is a breaking change but in my opinion it is OK.
