### ISSUE TITLE
Event handler exceptions

### ISSUE THREAD

**Issue by skairunner** [chkr1011/MQTTnet#855]
### Describe your question
Is there a way to have exception re-throwing? Currently if an event handler such as ApplicationMessageReceived throws an exception, the error is silently eaten and doesn't bubble up. Am I missing something obvious, or is this a limitation of the architecture?

### Which project is your question related to?
- Generic

**Comment by JanEggers** [comment]
Hi the exception cannot bubble up because that would crash the mqtt client. 
you can either attach a logger https://github.com/chkr1011/MQTTnet/wiki/Trace or write your own implementation of IMqttApplicationMessageReceivedHandler and handle the exception in there before it propagates back to the mqttclient code

**Comment by skairunner** [comment]
Good to know. Is it against spec to allow for optional MQTT client
crashing? It would be convenient for dev/testing purposes.

**Comment by JanEggers** [comment]
you could do something like this:

```csharp
MqttNetGlobalLogger.LogMessagePublished += (s, e) =>
{
    if (e.TraceMessage.Level == error)
    {
        Enviroment.FailFast(e.TraceMessage.Message);
    }
};
```

**Comment by chkr1011** [comment]
@skairunner Where should the exception bubble to? The client uses several threads internally to deal with messages etc. So if there is somewhere an exception to most "top" place is an internal worker thread. So you never will see it somewhere else. If this is not catched by us (the client) then the whole application will crash because of unhandled task exception (at least in .net 4.5.2). 

As @JanEggers already said you should catch exceptions in the message handler on your own.
