### ISSUE TITLE
Feature Request: Common interface of IMqttClient and IManagedMqttClient.

### ISSUE THREAD

**Issue by PMExtra** [chkr1011/MQTTnet#890]
I want a common interface of `IMqttClient` and `IManagedMqttClient`.

Or another solution: make `IMqttApplicationMessagePublisher` and `IMqttApplicationMessageReceiver`

What do you think?

**Comment by chkr1011** [comment]
We already have those interfaces for both types of clients. So they share functionality in a shared interface. Or do you mean something else?

**Comment by PMExtra** [comment]
Sorry for late.

I means I want `IManagedMqttClient` is assignable from `IMqttClient`.
Or we make both them is assgnable from `IMqttApplicationMessagePublisher` and `IMqttApplicationMessageReceiver`.

Because I want the mqttClient is replaceable in my high-level service that depends on MQTTnet.

**Comment by chkr1011** [comment]
I don't think that this is possible nor a good strategy at all. Both clients work completely different because the managed client gets "started" and then does everything on its own. The regular client requires more "interaction". So there is no chance to define a common interface for both. 

Apart from that I recommend that you just create your own interface. Then you can implement in properly two times for both clients. Then you can decide how to perform the required use cases. Having your own abstraction layer is generally a good advice because this lib might change APIs over time and in a far future you may want to replace this library entirely with a different one.

**Comment by PMExtra** [comment]
I've considered this solution but I've not thought so many advantage. Thanks for your advice.
