### ISSUE TITLE
Not connect SSL another clients as MQTTBox, ,mqtt-spy

### ISSUE THREAD

**Issue by Serjaru** [chkr1011/MQTTnet#893]
Try use another MQTT (as mqtt-spy, MQTT.fx) clients and while connect throw exception here:

```csharp
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private void ValidateReceiveBuffer(int length)
        {
            if (_length < _offset + length)
            {
                throw new ArgumentOutOfRangeException(nameof(_buffer), $"Expected at least {_offset + length} bytes but there are only {_length} bytes");
            }
        }
```

and get exception

> Event Type Moniker	Event	Time	Duration	Thread
> Activated Historical Code Context	Exception thrown: 'MQTTnet.Exceptions.MqttCommunicationException' in MQTTnet.dll ("Expected at least 770 bytes but there are only 3 bytes (Parameter '_buffer')") Exception thrown: 'MQTTnet.Exceptions.MqttCommunicationException' in MQTTnet.dll ("Expected at least 770 bytes but there are only 3 bytes (Parameter '_buffer')") Hyperlink: Activate Historical Debugging	17.54s		[26144] Worker Thread

**Comment by chkr1011** [comment]
Please share a code snipped to that we can try to reproduce the issue. 
Did you also use "UseTls" in the connection options builder?

**Comment by chkr1011** [comment]
It seems you did not 😄

**Comment by Serjaru** [comment]
> 
> 
> It seems you did not 😄

i found error and correct it.

but now error in DatabaseSetup

CREATE TABLE IF NOT EXISTS blacklist (
                id                      UUID            NOT NULL PRIMARY KEY,
                userid                  UUID            NOT NULL                REFERENCES user(id),
                type                    INTEGER         NOT NULL,
                value                   TEXT            NOT NULL,
                createdat               TIMESTAMPTZ     DEFAULT now(),
                updatedat               TIMESTAMPTZ     NULL,
                deletedat               TIMESTAMPTZ     NULL
            );

Error in SQL querys! in CreateStatements.cs
work only "CREATE TABLE IF NOT EXISTS databaseversion...."

Postgres 11

**Comment by SeppPenner** [comment]
@Serjaru I guess, you are posting this in the wrong project. This is something that belongs to one of my projects. Are you using https://github.com/SeppPenner/NetCoreMQTTExampleDapperConfig?

**Comment by SeppPenner** [comment]
@Serjaru Please use the latest version of my example project. I have fixed your issues in this commit: https://github.com/SeppPenner/NetCoreMQTTExampleDapperConfig/commit/4806b9c47a836913fc06abcdbb3ec54e6286e298.

**Comment by Serjaru** [comment]
I have questions yet about "NetCoreMQTTExampleJsonConfig".

1. the file in project "cert.pem" what is it for??
2. the file in project "key.pem" what is it for??
3. Can i run without validate client certificate? use only server certificate (certificate.pfx)?

**Comment by Serjaru** [comment]
and SeedData dont wait DeleteDatabase, CreateDatabase, CreateAllTables

and new user, blacklict, whitelist dont apply!

**Comment by Serjaru** [comment]
tables not fills example data

**Comment by SeppPenner** [comment]
@Serjaru As I already told you, you should open issues in the repositories your questions belong to... It's quite difficult for me to figure out what's wrong if I don't have enough information.

As far as I understood it now:

You used https://github.com/SeppPenner/NetCoreMQTTExampleDapperConfig and the `user` table wasn't created. This should be fixed now.

For the other issues:

* the file in project "cert.pem" what is it for?? --> This includes the public certificate. (Follow e.g. https://serverfault.com/questions/9708/what-is-a-pem-file-and-how-does-it-differ-from-other-openssl-generated-key-file for more information).
* the file in project "key.pem" what is it for?? --> This includes the private certificate. (Follow e.g. https://serverfault.com/questions/9708/what-is-a-pem-file-and-how-does-it-differ-from-other-openssl-generated-key-file for more information).
* Can i run without validate client certificate? use only server certificate (certificate.pfx)? --> This should be possible somehow, yes. E.g. follow https://github.com/chkr1011/MQTTnet/issues/124 or https://github.com/chkr1011/MQTTnet/wiki/Server#using-a-certificate for more information.
* and SeedData dont wait DeleteDatabase, CreateDatabase, CreateAllTables --> I don't understand what you mean with this?
* and new user, blacklict, whitelist dont apply! / tables not fills example data --> Can you tell me a bit more of what you did? (e.g. which of my example projects you are using, which database version of Postgres and maybe a bit more, e.g. an error message and so on.). Otherwise, I won't be able to help you. 

Also: Did you adjust the settings file for your database?
