### ISSUE TITLE
question about Server.WithClientId()

### ISSUE THREAD

**Issue by danielstock** [chkr1011/MQTTnet#916]
### Describe your question
in the wiki manual, it says that WithClientId() Sets the client id used for the server.

my test server has the following options:
var optionsBuilder = new MqttServerOptionsBuilder()
                    .WithConnectionBacklog(10)
                    .WithDefaultEndpointPort(8222)
                    .WithClientId("client001").....

and i used mqtt.fx  client to connect to it, with a generated clientid(b5eb47705c6440e09d7fc113bfb59e97) 

then i printed the clientid in the ClientConnectedHandler event.  the clientid is still the guid string, has nothing to do with the "client001".

thanks.

### Which project is your question related to?
 Server

**Comment by SeppPenner** [comment]
That's because the `WithClientId()` method of the server refers to the client id the server / broker uses for making requests. You're doing a request from the client to the server / broker.

Here is an image describing the situation:

![explanation](https://user-images.githubusercontent.com/9639361/81269149-37b76680-9049-11ea-909a-379c41ec76f9.png)

In this case, MQTT.fx would be the **MQTT-Client** and connects to the **MQTT-Broker**. If you have the use case that your server / broker, named **MQTT-Broker** in the example wants to connect to another broker (E.g. for clustering / bridging support or whatever), then you would need to set the client id of the server to let it connect to **Another MQTT-Broker**.

You can't change the client id a client uses to connect to your server / broker on the server side.

And here are the sources I used to generate this as well (In case we need this later again):
[explanation.zip](https://github.com/chkr1011/MQTTnet/files/4591522/explanation.zip)

@chkr1011 and @JanEggers Please correct me if I'm wrong here :)

**Comment by danielstock** [comment]
thanks a lot!
