### ISSUE TITLE
Code documentation (XML comments)

### ISSUE THREAD

**Issue by jacobusp** [chkr1011/MQTTnet#955]
### Describe the feature request
I see that all or almost all classes, methods and properties do not have XML documentation.
It would be really helpful to have an indication of what everything does while using the project, instead of having to search the documentation.

### Which project is your feature request related to?
All

### Describe the solution you'd like
In-code XML documentation like:
```
/// <summary>
/// Executed whenever the client is disconnected from the broker/server.
/// </summary>
public IMqttClientDisconnectedHandler DisconnectedHandler { get; set; }
```

### Additional context
I guess its not that helpful for very simple classes, properties or methods, but there are examples where it would be very useful:
`MqttClientOptionsBuilder` and `MqttApplicationMessageBuilder` have many options that could be documented in-code.

**Comment by SeppPenner** [comment]
@chkr1011 I guess, we already talked about this. I would like to see that as well, but there was some point against this if I remember correctly.

**Comment by chkr1011** [comment]
For me the problem is so find the sweet spot between useful and useless comments. I want to avoid comments like "Gets or sets the username" or "Gets or sets the Client ID" or "Gets or sets the password". These comments do not provide any value.

But as @jacobus mentioned complex things would benefit from some hints at the comment. But the main problem is that such comments must be maintained. Especially when they contain opinions, tips etc. Simple copies from official specs are not that intensive to maintain.

In the end time is the problem. If @jacobusp or @SeppPenner want to start adding those comments just do it and create a pull request. I am not "against" comments. But I also want them to be of good quality and this is currently not possible for me to deliver.

**Comment by touchofevil2** [comment]
@chkr1011 - If it is okay, I would like to help out with this. If that's alright could you please help out with if there is any specific guideline for PR/process for it?
